# Import Libraries and data

In [ ]:
import numpy as np
import pandas as pd
import plotly.express as px
from textblob import TextBlob

df=pd.read_csv('netflix_titles.csv.zip')

# Checking number of rows and columns in data

In [ ]:
df.shape

(8807, 12)

# Checking contents available in dataset

In [ ]:
df.head()

  show_id  ...                                        description
0      s1  ...  As her father nears the end of his life, filmm...
1      s2  ...  After crossing paths at a party, a Cape Town t...
2      s3  ...  To protect his family from a powerful drug lor...
3      s4  ...  Feuds, flirtations and toilet talk go down amo...
4      s5  ...  In a city of coaching centers known to train I...

[5 rows x 12 columns]

# How to check columns name of dataset

In [ ]:
df.columns

Index(['show_id', 'type', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description'],
      dtype='object')

# Taking the count of ratings available

In [ ]:
x = df.groupby(['rating']).size().reset_index(name='counts')
print(x)

      rating  counts
0     66 min       1
1     74 min       1
2     84 min       1
3          G      41
4      NC-17       3
5         NR      80
6         PG     287
7      PG-13     490
8          R     799
9      TV-14    2160
10      TV-G     220
11     TV-MA    3207
12     TV-PG     863
13      TV-Y     307
14     TV-Y7     334
15  TV-Y7-FV       6
16        UR       3

# Creating the Piechart based on Content rating

In [ ]:
pieChart = px.pie(x, values='counts',names='rating',title='Distribution of content ratings on Netflix')
pieChart.show()

# Analyzing the top 5 Directors on Netflix

In [ ]:
df['director']=df['director'].fillna('No Director Specified')
df.head()

  show_id  ...                                        description
0      s1  ...  As her father nears the end of his life, filmm...
1      s2  ...  After crossing paths at a party, a Cape Town t...
2      s3  ...  To protect his family from a powerful drug lor...
3      s4  ...  Feuds, flirtations and toilet talk go down amo...
4      s5  ...  In a city of coaching centers known to train I...

[5 rows x 12 columns]

In [ ]:
director_list = pd.DataFrame()
print(director_list)

Empty DataFrame
Columns: []
Index: []

In [ ]:
director_list = df['director'].str.split(',', expand=True).stack()
print(director_list)

0     0          Kirsten Johnson
1     0    No Director Specified
2     0          Julien Leclercq
3     0    No Director Specified
4     0    No Director Specified
                   ...
8802  0            David Fincher
8803  0    No Director Specified
8804  0          Ruben Fleischer
8805  0             Peter Hewitt
8806  0              Mozez Singh
Length: 9612, dtype: object

In [ ]:
director_list=director_list.to_frame()
print(director_list)

                            0
0    0        Kirsten Johnson
1    0  No Director Specified
2    0        Julien Leclercq
3    0  No Director Specified
4    0  No Director Specified
...                       ...
8802 0          David Fincher
8803 0  No Director Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [ ]:
director_list.columns=['Director']
print(director_list)

                     Director
0    0        Kirsten Johnson
1    0  No Director Specified
2    0        Julien Leclercq
3    0  No Director Specified
4    0  No Director Specified
...                       ...
8802 0          David Fincher
8803 0  No Director Specified
8804 0        Ruben Fleischer
8805 0           Peter Hewitt
8806 0            Mozez Singh

[9612 rows x 1 columns]

In [ ]:
directors = director_list.groupby(['Director']).size().reset_index(name='Total count')
print(directors)

                       Director  Total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5121 rows x 2 columns]

In [ ]:
directors = directors[directors.Director != 'No Director Specified']
print(directors)

                       Director  Total count
0                Aaron Moorhead            2
1                   Aaron Woolf            1
2      Abbas Alibhai Burmawalla            1
3              Abdullah Al Noor            1
4           Abhinav Shiv Tiwari            1
...                         ...          ...
5116                Çagan Irmak            1
5117           Ísold Uggadóttir            1
5118        Óskar Thór Axelsson            1
5119           Ömer Faruk Sorak            2
5120               Şenol Sönmez            2

[5120 rows x 2 columns]

In [ ]:
directors = directors.sort_values(by=['Total count'], ascending=False)
print(directors)

                 Director  Total count
4021        Rajiv Chilaka           22
4068          Raúl Campos           18
261             Jan Suter           18
3235         Marcus Raboy           16
4652          Suhas Kadav           16
...                   ...          ...
2330  Ivan Andrew Payawal            1
610    Songyos Sugmakanan            1
611          Sonia Dauger            1
612        Sophie Sartain            1
2335           Ivona Juka            1

[5120 rows x 2 columns]

In [ ]:
top5Directors = directors.head()
print(top5Directors)

           Director  Total count
4021  Rajiv Chilaka           22
4068    Raúl Campos           18
261       Jan Suter           18
3235   Marcus Raboy           16
4652    Suhas Kadav           16

In [ ]:
top5Directors = top5Directors.sort_values(by=['Total count'])
barChart = px.bar(top5Directors, x='Total count', y='Director', title='Top 5 Directors on Netflix')
barChart.show()

# Analyzing the top 5 Actors on Netflix

In [ ]:
df['cast']=df['cast'].fillna('No Cast Specified')
cast_df = pd.DataFrame()
cast_df = df['cast'].str.split(',', expand=True).stack()
cast_df = cast_df.to_frame()
cast_df.columns = ['Actor']
actors = cast_df.groupby(['Actor']).size().reset_index(name='Total count')
actors = actors[actors.Actor != 'No Cast Specified']
actors = actors.sort_values(by=['Total count'], ascending=False)
top5Actors = actors.head()
top5Actors = top5Actors.sort_values(by=['Total count'])
barChart2 = px.bar(top5Actors, x='Total count', y='Actor', title='Top 5 Actors on Netflix')
barChart2.show()

# Analyzing the content produced on netflix based on years

In [31]:
df1 =  df[['type','release_year']]
df1 = df1.rename(columns ={"release_year":"Release Year","type":"Type"})
df2 = df1.groupby(['Release Year','Type']).size().reset_index(name='Total Count')
print(df2)

     Release Year     Type  Total Count
0            1925  TV Show            1
1            1942    Movie            2
2            1943    Movie            3
3            1944    Movie            3
4            1945    Movie            3
..            ...      ...          ...
114          2019  TV Show          397
115          2020    Movie          517
116          2020  TV Show          436
117          2021    Movie          277
118          2021  TV Show          315

[119 rows x 3 columns]

In [34]:
df2 = df2[df2['Release Year']>=2000]
graph = px.line(df2, x="Release Year", y="Total Count", color='Type',title= "Trend of Content Produced on Netflix Every Year")
graph.show()

# Sentiment Analysis of Netflix Content

In [45]:
df3 = df[['release_year','description']]
df3 = df3.rename(columns={'release_year':'Release Year','description':'Description'})
for index, row in df3.iterrows():
  d=row['Description']
  testimonial = TextBlob(d)
  p = testimonial.sentiment.polarity
  if p==0:
    sent = 'Neutral'
  elif p>0:
    sent = 'Positive'
  else:
    sent = 'Negative'
  df3.loc[[index],'Sentiment']=sent

df3 = df3.groupby(['Release Year','Sentiment']).size().reset_index(name='Total Count')
df3  = df3[df3['Release Year']>=2005]
barGraph = px.bar(df3, x='Release Year', y='Total Count', color='Sentiment', title="Sentiment Analysis of Content on Netflix")
barGraph.show()